SeaGL/seagl-terraform

dns.tf
- point `alias.` to the same IP as `osem.`
=> add alias.seagl.org for matrix aliasing

rds.tf, s3.tf
- making sure s3 bucket ACLs were imported
- making sure MariaDB version is correct
- making sure DNS entries are also correct
=> Whoops needa branch

s3.tf
- skip ACL, not needed when set to private
- add 120 versioning retention
=> enable versioning, skip ACL

moved.tf, osem_rds/main.tf, osem_rds/output.tf, osem_rds/sgs.tf, osem_rds/variables.tf, rds.tf
This is in preparation to set up a second OSEM for sandbox purposes.
=> Move the OSEM db into a module

dns.tf
See https://github.com/osuosl-cookbooks/proj-seagl/issues/1#issuecomment-1560145391
=> Create OSUOSL Nextcloud records

.gitignore, .terraform.lock.hcl, get-creds.sh, provider.tf
=> Hook up Terraform to OpenStack

.github/workflows/terraform.yaml
=> Give GitHub Actions OpenStack credentials

dns.tf
Ref SeaGL/organization#325, followup to #25
=> Add additional test Mailu DNS records

mailu.tf
This generates a clean plan with the following Terraform command:
terraform import openstack_compute_instance_v2.mailu a387a626-5182-4ae9-947b-a0a58ffa0ca6
DO NOT MERGE until #28 lands because I want to rebase this on top of that commit and look at the generated `plan`, just in case. Marking PR as draft to prevent accidents.
=> Import Mailu OpenStack instance

dns.tf
re [discussion in Matrix](https://matrix.to/#/!GkthNMOKdgiNHAErwB:seattlematrix.org/$bZPy87ISVLXENDHvFObzBfwkWkFb52rdJVXB2nesToA?via=seattlematrix.org)
=> Add HubSpot DNS records

dns.tf
See https://github.com/osuosl-cookbooks/proj-seagl/issues/1#issuecomment-1633355485
=> Authorize OSUOSL to send mail

dns.tf
See https://www.mail-tester.com/test-8asv2y5hx&reloaded=1
=> Fix Nextcloud SPF (again)

dns.tf, imports.tf, mailu.tf, nextcloud-office.tf
`plan` locally shows no changes besides the import.
=> Import seagl.org Route 53 zone

osem_rds/main.tf
Followup to #50; should fix AWS nag emails about this.
=> Bump RDS CA version

dokku.tf
I did this manually in the console a few weeks ago in response to some instability due to us deploying so many apps.
=> Bump Dokku instance size

osem_rds/main.tf, pretalx-rds.tf
=> enable deletion protection on osem and pretalx rds instances

simple_vm/main.tf
This is causing errors in #76.
=> Fix Ubuntu 22.04 image ID in simple_vm/

dns.tf
This reverts commit 6565cecd683326060ebfb9e9d1d376846d86101a.
=> Revert "Add Jitsi Meet A DNS record"

env/shell.tf
The idea is that this is a place where people can have a `~/public_html` and set up cronjobs and random convenient stuff like that, in case they don't already have their own server.
=> Set up a shell server

env/shell.tf, simple_vm/main.tf, simple_vm/variables.tf
=> Open ports 7000-8000 on shell.host

env/docker-cluster.tf
Ansible needs this (and we still want to use Ansible to manage users).
=> Install Python on CoreOS first boot
